#adding SOMETHING something
#adding SOMETHING something
#adding SOMETHING something

version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.12.5
  
jobs:
  build_and_test:
    executor: node/default

    # environment:
    #   MY_API_KEY: $MY_API_KEY

    steps:
      - checkout
      # - run:
      #     name: testing context env
      #     command: echo $MY_API_KEY

      - node/install-packages:
          pkg-manager: npm

      - run:
            command: printenv
            name: Print Environment Variables


      
      # - run:
      #       command: npm test
      #       name: Test

      # - slack/notify:
      #     channel: ci-cd
      #     event: fail
      #     template: basic_fail_1
      #     custom: | # your custom notification goes here
      #         {
      #           "blocks": [
      #           {
      #             "type": "section",
      #             "fields": [
      #         {
      #           "type": "plain_text",
      #           "text": "*This is a text notification*",
      #           "emoji": true
      #         }
      #         ]
      #           }
      #             ]
      #               }

      # - run:
      #     command: npm run config-react-native
      #     name: Build App
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - .
  
  on_hold_feature:
      docker:
      - image: cimg/base:2022.03
      steps:
        - checkout
        - run: echo 'waited for approval'
            

workflows:
  build:
    jobs:
      - build_and_test:
          context: slack-secrets
          type: approval
          
      - on_hold_feature:
          requires:
            - build_and_test
