version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.2.0
  
jobs:
  build_and_test:
    executor: node/default

    environment:
      MY_API_KEY: $MY_API_KEY

    steps:
      - checkout
      - run:
          name: testing context env
          command: echo $MY_API_KEY

      - node/install-packages:
          pkg-manager: npm

      - run:
            command: printenv
            name: Print Environment Variables
      
      - run:
            command: npm test
            name: Test

      - slack/notify:
          channel: CI-CD
          event: fail
          template: basic_fail_1
          attachments: |
            [
              {
                "title": "Test Failure",
                "text": "One or more tests failed in the build.",
                "color": "#FF0000"
              }
            ]

      - run:
          command: npm run config-react-native
          name: Build App
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build:
    jobs:
      - build_and_test:
          context: Sample_Context
